/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cityzen.form;
import com.cityzen.dao.NhanVienDao;
import com.cityzen.entity.NhanVien;
import com.cityzen.ultils.Auth;
import com.cityzen.ultils.MsgBox;
import com.cityzen.ultils.XImage;

/**
 *
 * @author QUANG
 */
public class DangNhapForm extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhapForm() {
        initComponents();
        setIconImage(XImage.APP_ICON);
        this.setTitle("Đăng nhập");
        setLocationRelativeTo(null);
    }
    
    NhanVienDao dao = new NhanVienDao();
    
    void login() {
        String manv = txtMaNhanVien.getText();
        String matKhau = new String(txtMatKhau.getPassword());
        try {
            NhanVien nhanVien = dao.findById(manv);
            
            if (nhanVien != null) {
                String matKhau2 = nhanVien.getMatKhau();
                if (matKhau.equals(matKhau2)) {
                    Auth.user = nhanVien;
                    new MainForm().setVisible(true);
                    this.dispose();                   
                } else {
                    MsgBox.alert(this, "Sai mật khẩu!");
                    System.out.println(matKhau);
                    System.out.println(matKhau2);
                }
            } else {
                MsgBox.alert(this, "Mã nhân viên không tồn tại!");
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Login Lỗi truy vấn dữ liệu!");
            e.printStackTrace();
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMatKhau = new javax.swing.JLabel();
        txtMaNhanVien = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblMaNhanVien = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        btnDangNhap = new javax.swing.JButton();
        lblQuenMatKhau = new javax.swing.JLabel();
        lblQr = new javax.swing.JLabel();
        lblQR = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblAnimation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMatKhau.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setText("Mật khẩu:");
        getContentPane().add(lblMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        txtMaNhanVien.setBackground(new java.awt.Color(0, 162, 255));
        txtMaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        txtMaNhanVien.setBorder(null);
        getContentPane().add(txtMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 490, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(10.0F);
        jSeparator1.setAlignmentY(10.0F);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 490, 10));

        lblMaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien.setText("Mã nhân viên:");
        getContentPane().add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        txtMatKhau.setBackground(new java.awt.Color(0, 162, 255));
        txtMatKhau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setBorder(null);
        getContentPane().add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 500, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setAlignmentX(10.0F);
        jSeparator2.setAlignmentY(10.0F);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 490, 10));

        btnDangNhap.setBackground(new java.awt.Color(0, 162, 255));
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 510, 130, -1));

        lblQuenMatKhau.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuenMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblQuenMatKhau.setText("Quên mật khẩu?");
        lblQuenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQuenMatKhauMousePressed(evt);
            }
        });
        getContentPane().add(lblQuenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, -1, -1));

        lblQr.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQr.setForeground(new java.awt.Color(0, 153, 255));
        lblQr.setText("Đăng nhập bằng mã QR");
        lblQr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQrMousePressed(evt);
            }
        });
        getContentPane().add(lblQr, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, -1));

        lblQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cityzen/icon/qr.png"))); // NOI18N
        lblQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblQRMousePressed(evt);
            }
        });
        getContentPane().add(lblQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 540, -1, -1));

        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cityzen/icon/portrait.png"))); // NOI18N
        getContentPane().add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, -1, -1));

        lblAnimation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/cityzen/icon/water2.gif"))); // NOI18N
        getContentPane().add(lblAnimation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblQuenMatKhauMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuenMatKhauMousePressed
        new DoiMatKhauForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblQuenMatKhauMousePressed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        login();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblQrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQrMousePressed
        CamQR qr = new CamQR();
        qr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQrMousePressed

    private void lblQRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQRMousePressed
        CamQR qr = new CamQR();
        qr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblQRMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAnimation;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblQR;
    private javax.swing.JLabel lblQr;
    private javax.swing.JLabel lblQuenMatKhau;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JPasswordField txtMatKhau;
    // End of variables declaration//GEN-END:variables
}
